### Numpy 기초

- 넘파이 패키지 로드 
import numpy as np

In [2]:
import numpy as np

### Python 리스트 (배열)과 Numpy 배열비교

- 파이썬에 기존 리스트 (배열) 자료구조 존재, 속도적면에서 Numpy가 우세

### 파이썬으로 배열작업

In [5]:
prices = [10000, 15000, 12000, 30000, 25000]  # 5개의 가격이 든 배열
discount_prices = []

for price in prices:
    discount_prices.append(price * 0.9) # 10% 할인

discount_prices # 노트북 코드쉘에서 하나만 출력하려면 print() 생략가능

[9000.0, 13500.0, 10800.0, 27000.0, 22500.0]

 ### 넘파이로 배열작업

In [27]:
import numpy as np

prices = [10000,15000, 12000, 30000, 25000]

np_prices = np.array(prices) # 넘파이 배열로 변경
np_discount_prices = np_prices * 0.9

np_discount_prices.tolist()

[9000.0, 13500.0, 10800.0, 27000.0, 22500.0]

-numpy 배열은 반복문을 사용하지 않아도 배열 전체에 계산을 수행할 수 있음. 벡터화 연산

### Numpy 배열생성

In [28]:
array= np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [29]:
# 2차원 배열
sales= np.array ([
    [100,120,130],
    [90,120,150],
    [80,140,160]
])

sales

array([[100, 120, 130],
       [ 90, 120, 150],
       [ 80, 140, 160]])

In [34]:
tests =  [
    [100, 120, 130],
    [90, 110, 150],
    [80, 140, 160]
]

print(tests)
print(np.array(tests)) # 두개 실행 다 되게 하려면 print를 무조건 써야한다

[[100, 120, 130], [90, 110, 150], [80, 140, 160]]
[[100 120 130]
 [ 90 110 150]
 [ 80 140 160]]


#### 배열 기본 속성

- ndim : 배열의 차원수
- shape: 배열 행과 열의 구조
- size: 전체 데이터 수
- dtype: 배열에 저장된 데이터 타입


In [31]:
#ndim
print(np_prices.ndim, sales.ndim)

1 2


In [32]:
#shape  행과 열의 구조
np_prices.shape

(5,)

In [33]:
sales.shape

(3, 3)

In [35]:
np_prices.size

5

In [36]:
sales.size

9

In [37]:
np_prices.dtype

dtype('int64')

In [38]:
sales.dtype

dtype('int64')

#### Numpy 데이터타입

- int8 : -128 ~ 127 (총 256)
- int16 :-32768 ~ 32767 (총 65536)
- int32 : 32 비트정수
- int64 : 64 비트정수  (numpy 기본 정수)
- uin8 : 0 ~ 255
- uint16: 0 ~ 65536
- float 16 : 상수
- float 32 : 32 비트 상수
- float 64 : 64 비트 상수  (numpy 기본 상수)
- complex64 : 복소수
- complex128: 128 비트 복소수
- bool: true/ false
- str_: 문자열
- object_: 객체


#### 배열 생성 

- 0이나 1로 챠워진 기본 배열 생성함수

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [42]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.linspace(0,1,5) #균등배열 (표준편차 등)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### 배열 연산

In [50]:
data= np.array([10,20,30,40,50])

In [51]:
#사칙연산
data+10

array([20, 30, 40, 50, 60])

In [52]:
data-10

array([ 0, 10, 20, 30, 40])

In [53]:
data*2

array([ 20,  40,  60,  80, 100])

In [54]:
data/2

array([ 5., 10., 15., 20., 25.])

In [56]:
#배열끼리 연산
# 배열끼리 연산
quantity = np.array([2, 1, 3, 5, 4])
unit_price = np.array([10000, 15000, 12000, 8000, 20000])

sales_price = unit_price * quantity
sales_price

array([20000, 15000, 36000, 40000, 80000])

#### 기본 통계함수

- 평균 최대/ 최소값 중앙값 표준편차 등


scores= np.array([80,95,70,60,100,80])

In [59]:
scores = np.array([80, 90, 75, 100])

np.sum(scores)

np.int64(345)

In [60]:
np.max(scores)

np.int64(100)

In [61]:
np.min(scores)

np.int64(75)

In [62]:
np.median(scores)

np.float64(85.0)

In [63]:
np.std(scores)

np.float64(9.60143218483576)

### 인덱싱 / 슬라이싱

- 파이썬 배열에서 기능과 유사

In [64]:
data

array([10, 20, 30, 40, 50])

In [ ]:

# 인덱싱
data[1]

np.int64(20)

In [66]:
data[4]

np.int64(50)

In [68]:
data[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [67]:
data[-1]

np.int64(50)

In [69]:
# 슬라이싱

data[:] # 배열전체

array([10, 20, 30, 40, 50])

In [ ]:
data[1:4] # 뒤의 수는 n-1까지 인덱스 추출

array([20, 30, 40])

In [71]:
data [:3]

array([10, 20, 30])

In [72]:
data[4:]

array([50])

In [73]:
# 2차원 배열 

sales

array([[100, 120, 130],
       [ 90, 120, 150],
       [ 80, 140, 160]])

In [74]:
sales[0,0] #0 번열 값 인덱싱


np.int64(100)

In [ ]:
sales[1,:] #1번 행의 모든 열을 슬라이싱

array([ 90, 120, 150])

In [78]:
sales[:,2] #모든행의 2번열을 슬라이싱

array([130, 150, 160])

#### 조건 필터링

- sql where절과 동일, 조건에 맞는 데이터만 골라내기

In [81]:
np_prices 

array([10000, 15000, 12000, 30000, 25000])

In [82]:
np_prices>= 20000

array([False, False, False,  True,  True])

In [83]:
condition = np_prices >=20000
condition

array([False, False, False,  True,  True])

In [84]:
np_prices[condition]

array([30000, 25000])

In [86]:
np_prices[np_prices >= 20000]

array([30000, 25000])

In [88]:
datas =np.array([10,-2,80,999,30,120])
datas


array([ 10,  -2,  80, 999,  30, 120])

In [91]:
data[(data >= 0) & (data <= 100)]

array([10, 80, 30])

### 결측값 핸들링

- 실제 데이터에서 값이 비어있는 경우 이를 결측치/ 결측값이라고 함
- 일반적으로 NULL 파이썬에서는 None, Numpy에서는 'np.nan'로 표현